### ISSUE TITLE
Lets unlock gunz gunx

### ISSUE THREAD

**Issue by Swanidius** [msh100/ETPro-configs#19]
As title says. Lets unlock gun position for ppl who desire that!

Why it is even locked 1st place? someone has greater info about this?!

**Comment by msh100** [comment]
These are cheat protected cvars. I can't find any reason why this is and it's nothing to do with the config set.

Id protected this in ioquake3 so I have no doubt they had a good reason for it (I have no idea what it is however).

**Comment by msh100** [comment]
Not worth the debate imo, not possible in any Quake 3 game

**Comment by ohurcool** [comment]
it changes the position of not only the gun but where the bullets come from as well, allowing you to shoot around corners and over/under things

**Comment by msh100** [comment]
I don't believe that, proof?

**Comment by ohurcool** [comment]
read it on CF before

100% works with the flamethrower, dunno about smg

**Comment by miraya** [comment]
@ohurcool this was fixed later in some ET patch, but the gunx guny and gunz only dictate the hud position of the gun, doesn't modify anything related to the server perceiving the players crosshair position regardless.

@msh100 The reason it's cheat protected I think dates back to the Q3 bug, wasn't fixed at that time so still locked.

**Comment by ohurcool** [comment]
are you sure? when/how was it "patched"? http://www.crossfire.nu/journals/91862/cg-gunx

**Comment by msh100** [comment]
@miraya I absolutely can not see the advantage of having it unlocked still. The ability to not draw it at all still exists. I don't understand why the cvar wouldn't have been unlocked in later versions of ioq3 in that case (a fixed bug) as it is still locked in newer games on this engine.

**Comment by miraya** [comment]
@msh100 Regarding your comment, I fully agree with you that it should be kept locked for the reasons already mentioned by others and I see no advantage over trying to unlock it, which is even impossible given the thing we are working on.

@msh100 Didn't 2.60b/c or ET:L fix it? I haven't really followed the scene really at all after Q1-2013. I might be wrong, about the actual bug considering you can shoot around corners, but afaik it only worked on flamethrower, no?
